### ISSUE TITLE
separate db access from data transformation

### ISSUE THREAD

**Issue by chfin** [DCMLab/tree-annotation-code#7]
Operations on the data structure in the database should be pure functions and just return the new data structure. Updating/dereferencing the db ref should be a separate step.

**Comment by dharasim** [comment]
That sounds good. I just find it hard sometimes to draw the boundary here. My priority was to write queries that don't expose the structure of the database outside of its namespace. But I'm sure there are query functions in the code that could be refactored into a pure function and a more primitive database update. Do you have specific examples of those?

**Comment by chfin** [comment]
I'll have a look through the code. If I find a consistent way to do this, I'll make a PR.

**Comment by dharasim** [comment]
Nice!

**Comment by chfin** [comment]
solved by #11
